routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/admin', function () {
    return view('layouts.vali');
});

Route::resource('order', 'OrdersController');
Route::resource('category', 'CategoryController');
Route::resource('vendors', 'VendorController');
Route::get('/data-orders', 'CekOrderController@index')->name('data.order');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Orders.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Orders extends Model
{
    protected $table = 'orders';
    protected $guarded = [];

}

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\StoreOrderPost;
use App\Orders;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Orders::latest()->get();

        try {
            $data = [
                'code' => 200,
                'status' => 'success',
                'data' => $orders
            ];
            return response()->json($data);

        }catch (\Exception $exception){
            $data = [
                'code' => 404,
                'status' => 'failed',
            ];
            return response()->json($data);
        }
    }

    public function store(StoreOrderPost $request)
    {
        $validated = $request->validated();
        try {
            Orders::create($validated);
            $data = [
              'code' => '401',
              'status' => 'Create Order Successfully',
              'data' => $validated
            ];

            return response()->json($data);
        } catch (\Exception $exception) {
            $data = [
                'code' => '400',
                'status' => 'Failed',

            ];

            return response()->json($data);
        }
    }

    public function edit($id)
    {
        $orders = Orders::find($id);
        try {
            $data = [
              'code' => '200',
              'status' => 'success',
              'data' => $orders
            ];

            return response()->json($data);
        } catch (\Exception $exception){
            $data = [
                'code' => '404',
                'status' => 'failed',
            ];

            return response()->json($data);
        }
    }

    public function update(Request $request, $id)
    {

        $order = Orders::find($id);
        try {

            $order->update([
                'status' => $request->status
            ]);
            $data = [
                'code' => '200',
                'status' => 'Update Order Successfully',

            ];

            return response()->json($data);
        } catch (\Exception $exception) {
            $data = [
                'code' => '400',
                'status' => 'Failed',
            ];

            return response()->json($data);
        }
    }

    public function destroy(Orders $orders)
    {
        try {
            $orders->delete();
            $data = [
                'code' => '400',
                'status' => 'Deleted Order Successfully',
                'data' => $orders
            ];
            return response()->json($data);
        } catch (\Exception $exception) {
            $data = [
                'code' => '404',
                'status' => 'Deleted Order Failed',
            ];
            return response()->json($data);
        }
    }
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StoreOrderPost;
use App\Orders;
use App\Vendor;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Orders::latest()->get();


        return view('orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrderPost $request)
    {
        $validated = $request->validated();
        Orders::create($validated);
        try {

            Session::flash('success', 'Create Order Success');
            return redirect()->route('order.index');
        }catch (\Exception $exception) {
            Session::flash('error', 'Create Order Gagal');
            return redirect()->route('order.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Orders  $postOrders
     * @return \Illuminate\Http\Response
     */
    public function show(Orders $postOrders)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Orders  $postOrders
     * @return \Illuminate\Http\Response
     */
    public function edit(Orders $order)
    {
        $orders = Orders::find($order->id);

        return view('orders.edit', compact('orders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Orders  $postOrders
     * @return \Illuminate\Http\Response
     */
    public function update(StoreOrderPost $request, $id)
    {

        $validated = $request->validated();
        try {
           $order = Orders::find($id);
               $order->update($validated);
            Session::flash('success', 'Update Order Success');
            return redirect()->route('order.index');
        }catch (\Exception $exception) {
            Session::flash('error', 'Update Order Gagal');
            return redirect()->route('order.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Orders  $postOrders
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = Orders::find($id);

        try {
            $order->delete();
            Session::flash('success', 'Delete Order Success');
            return redirect()->route('order.index');
        }catch (\Exception $exception) {
            Session::flash('error', 'Delete Order Gagal');
            return redirect()->route('order.index');
        }
    }
}

resources/views/Orders/create.blade.php
@extends('dashboard.layout')
@section('header')
    Request Order
@endsection
@section('content-dashboard')

    <div class="row">
        <div class="col-md-6">
            <div class="tile">
                <form action="{{ route('order.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label for="nama_barang">Nama Barang</label>
                        <input class="form-control" id="nama_barang" name="nama_barang" type="text" >
                    </div>
                    <div class="form-group">
                        <label for="jumlah">Jumlah</label>
                        <input class="form-control" id="jumlah" name="jumlah" type="number" >
                    </div>

                    <div class="tile-footer ">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/Orders/edit.blade.php
@extends('dashboard.layout')
@section('header')
    Edit Order - {{ $orders->nama_barang }}
@endsection
@section('content-dashboard')

    <div class="row">
        <div class="col-md-6">
            <div class="tile">
                <form action="{{ route('order.update', $orders->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="nama_barang">Nama Barang</label>
                        <input class="form-control" value="{{ $orders->nama_barang }}" id="nama_barang" name="nama_barang" type="text"  placeholder="Enter name">
                    </div>
                    <div class="form-group">
                        <label for="jumlah">Jumlah</label>
                        <input class="form-control" value="{{ $orders->jumlah }}"  id="jumlah" name="jumlah" type="text"  placeholder="Enter name">
                    </div>

                    <div class="tile-footer">
                        <button class="btn btn-primary" type="submit">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/Orders/index.blade.php
@extends('dashboard.layout')
@section('content-dashboard')

    <div class="row">
        <div class="col-md-12">

            <div class="tile">
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <div class="float-right">
                            <a href="{{ route('order.create') }}" class="btn btn-outline-primary">Buat Order</a>
                        </div>
                    </div>
                </div>
                <div class="tile-body">
                    <table class="table table-hover table-bordered" id="sampleTable">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Tgl Request</th>
                            <th>Name</th>
                            <th>Jumlah</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($orders as $order)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $order->created_at }}</td>
                            <td>{{ $order->nama_barang }}</td>
                            <td>{{ $order->jumlah }}</td>
                            <td>{{ $order->status }}</td>

                            <td>
                                <a href="{{ route('order.edit', $order->id) }}" class="btn btn-sm btn-outline-primary">Edit</a>
                                <button onclick="deleteItem({{ $order->id }})" class="btn btn-sm btn-outline-danger">Delete</button>
                            </td>
                        </tr>
                            @empty
                        <tr>
                            <td colspan="7" class="text-center">Tidak ada data</td>
                        </tr>
                        @endforelse

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @push('js')
        <script src="{{ asset('vendor/js/plugins/pace.min.js') }}"></script>
        <!-- Page specific javascripts-->
        <!-- Data table plugin-->
        <script type="text/javascript" src="{{ asset('vendor/js/plugins/jquery.dataTables.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('vendor/js/plugins/dataTables.bootstrap.min.js') }}"></script>
        <script type="text/javascript">$('#sampleTable').DataTable();</script>

        <script>
            function deleteItem(id) {
                let theUrl = "{{ route('order.destroy', ':id_order') }}"
                theUrl = theUrl.replace(':id_order', id);

                swal({
                    title: "Apakah anda yakin?",
                    text: "Menghapus file ini",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel plx!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: theUrl,
                            data: {
                                "_method": 'DELETE',
                            },
                            success: function (data) {
                                swal("Deleted!", "Data Sukses di delete", "success");
                                window.location.reload()
                            },
                            error: function (data) {
                                console.log(data);
                                swal("Failed", "File gagal di delete)", "error");
                            }
                        })

                    } else {
                        swal("Cancelled", "File gagal di delete)", "error");
                    }
                });
            }
        </script>
    @endpush
@endsection